version: 1.2
workflows:
  - name: WholeGenomeGermlineSingleSample
    subclass: WDL
    primaryDescriptorPath: /pipelines/broad/dna_seq/germline/single_sample/wgs/WholeGenomeGermlineSingleSample.wdl
  - name: DragenTools
    subclass: WDL
    primaryDescriptorPath: /tasks/broad/Dragen.wdl
